### ISSUE TITLE
pwcli to hscli?

### ISSUE THREAD

**Issue by avelino** [hoppscotch/hopp-cli#15]
Since it was changed from PostWoman to Hoppscotch will change the name of this project?

**Comment by athul** [comment]
Hey, I was planning to name it as hopp rather than add a cli prefix. What do you say?
cc: @liyasthomas

**Comment by liyasthomas** [comment]
hopp or or hopp-cli sounds good to me. But I second hopp-cli cause it makes more sense.

**Comment by athul** [comment]
Oh okay, Will rename it today

**Comment by liyasthomas** [comment]
@athul lets this be hopp-cli. I got another plan for hoop repo.
