### ISSUE TITLE
Script doesn't work on Arch.

### ISSUE THREAD

**Issue by cocoonkid** [hoppscotch/hopp-cli#25]
It doesn't error either but the binary is nowhere to be found.

It would be great to submit a package to AUR.

I fixed it by downloading and moving the binary directly.

**Comment by athul** [comment]
Hey, thanks for opening this bug. I'll look into it and get back to you.
I don't have any experience in packaging for AUR 😢😢

.deb and .rpm can be done with Goreleaser.

**Comment by cocoonkid** [comment]
https://wiki.archlinux.org/index.php/Creating_packages 
:-)

If I have time I could do it once but I don't have time to maintain it in the long run.

I'll look into it asap! Thanks anyway!

**Comment by cocoonkid** [comment]
:clap:
