### ISSUE TITLE
FEAT: Add support for inserting request body through external editor

### ISSUE THREAD

**Issue by devblin** [hoppscotch/hopp-cli#41]
Currently, for making request with request body with have to add the data in inline mode like this: **`'{"name": "morp","job": "zion resident"}'`** this is good for small data, but for more request data user may want better way.
For above mentioned problem, we add support for using external editor with default file (to take input for request data).
So, basically if the user wants to add data through editor, they can use a flag.

**Comment by devblin** [comment]
@liyasthomas , if the feature seems good, you can assign me this to work on 👍🏽

**Comment by liyasthomas** [comment]
@AndrewBastin thoughts on this?

**Comment by athul** [comment]
@devblin That is a good idea. Your'e planning to use the`$EDITOR` posix variable right?

**Comment by devblin** [comment]
@athul , Yes, but as its path value could be for **vim** which I guess isn't suitable for beginners, we may need to use either **nano** or **gedit** in case of Linux and similarly for WIN and Mac

**Comment by athul** [comment]
I'm curious on how you plan to implement this. If you could share the way on the same before a PR is made, it would be great.

**Comment by devblin** [comment]
@athul , Yes sure, so we will have a flag for adding request body in default file (REQUEST_BODY.txt) through text-editor, the tool will wait for the file to close, and after that it will read the contents of file.

**Comment by athul** [comment]
Seems legit. Suggestion: Use a temp file for the placeholder(`REQUEST_BODY.txt`) file. You can start on this 👍
