### ISSUE TITLE
Update Goreleaser

### ISSUE THREAD

**Issue by athul** [hoppscotch/hopp-cli#46]
Hopp-cli uses goreleaser version and yml from 2019 🙈 . We want to update the goreleaser.yml file for better releasing and packaging. If anyone is willing to take this up, would be great. 

For further questions you can ping me,  making this an issue due to a backlog of changes

**Comment by ashique-perumbavoor** [comment]
I don't understand what you are trying to achieve here. What do you mean by better releasing and packaging?

**Comment by athul** [comment]
New Goreleaser versions have made it possible for packaing for M1 macs while the goreleaser version currently we have just builds for Intel macs. Plus iirc goreleaser supports macos universal binaries too(we won't be needing that though 😅 )

**Comment by BRO3886** [comment]
I can try it out this weekend. Need to do something similar for one of my personal projects too

**Comment by ashique-perumbavoor** [comment]
@BRO3886  I have done some of the work, But I am busy with some other work. I would like to invite you to finish it. [Pull Request](https://github.com/hoppscotch/hopp-cli/pull/48)

**Comment by athul** [comment]
Closed due to #49
